### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by iielse** [leon2017/GankJetpack#1]
06-11 09:21:41.701 10242-10242/com.wangjun.gankjetpack E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.wangjun.gankjetpack, PID: 10242
                                                                         java.lang.IllegalArgumentException: Unknown pattern character 'X'
                                                                             at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
                                                                             at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
                                                                             at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
                                                                             at com.wangj.kotlin.app.utils.TimeUtilKt.getTime(TimeUtil.kt:23)
                                                                             at com.wangjun.gankjetpack.ui.adapter.GankCategoryAdapter$GankViewHolder.bindView(GankCategoryAdapter.kt:55)

**Comment by leon2017** [comment]
thanks your suggestion , has fixbug ^_^!!!
